steps:
# 1. Build & Push Checkout Service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/checkout-service:$COMMIT_SHA', './services/checkout']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/checkout-service:$COMMIT_SHA']

# 2. Build & Push Search Service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/search-service:$COMMIT_SHA', './services/search']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/search-service:$COMMIT_SHA']

# 3. Run Unit Tests
- name: 'golang:1.21'
  entrypoint: 'go'
  args: ['test', './services/...', '-v']

# 4. Deploy to Staging (GKE)
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/deployments/', '-n', 'staging']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_REGION}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

# 5. Automated Load Test (k6) - Regression Gate
# Uses a custom k6 runner image or installs k6
- name: 'grafana/k6:latest'
  entrypoint: 'k6'
  args: ['run', 'tests/load/k6-script.js']
  env:
  - 'K6_OUT=json=test_results.json'

# 6. Deploy to Production (Only if previous steps pass)
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/deployments/', '-n', 'production']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_REGION}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

substitutions:
  _REGION: us-central1
  _CLUSTER_NAME: grocery-platform-cluster
timeout: 1200s
